### PR TITLE
Implement GeneratedHydrators with AbstractHydrator as base class

### PR DESCRIPTION
**Pull request by mordilion**
To allow the usage of Strategies, I implemented a CodeGenerator to use the AbstractHydrator as the base class. In that way, it's also possible to hydrate recursively with the new RecursiveHydrationStrategy, which is also part of this Pull-Request.

### CODE REVIEW

**Comment by Ocramius** [comment]
@mordilion that's a lot of work you've done here, but I don't think the generated hydrator should have strategy logic in it: if needed, it should instead be **wrapped** in a hydrator capable of such things, IMO...

**Comment by mordilion** [comment]
Thanks for your Feedback @Ocramius! We are using your library to get the performance benefit. Unfortunately, we have a lot of models with nested models, why we need actually the recursive hydration functionality. I thought it would be maybe a benefit for you and others. :) 

Have you maybe an example of how you would do such recursive hydration without strategies?

**Comment by Ocramius** [comment]
> Have you maybe an example of how you would do such recursive hydration without strategies?

Good question: would probably use a top-level hydrator that extracts (recursively) using multiple generated hydrators.

Something like:

```hs
extractWithGeneratedHydrator :: object -> (object -> array) -> array
hydrateWithGeneratedHydrator :: array -> (array -> object) -> array
```

So your "external" hydrator could use a `Map<class-string<ObjectTypeToHydrate>, HydrateInterface>` and `Map<array, class-string<ObjecTypeToHydrate>>` to define which generated hydrators to use internally.

**Comment by pounard** [comment]
@mordilion 

I needed that as well, despite the fact I agree with @Ocramius this should be in your business factory layer and not in the generated hydrator itself.

See https://github.com/makinacorpus/generated-hydrator-bundle/blob/master/src/DeepHydrator.php

Basics are, I extracted a custom `HydratorInterface` for plugging generated-hydrator to Symfony, this interface is implemented by a `DefaultHydrator` that only glues framework given configuration in order to bridge generated-hydrator, and `NestedHydrator` that hydrate recursively at runtime (recursion is not a generated algorithm) but performance wise, it's still good.

**Comment by mordilion** [comment]
@pounard 
Thanks for your message, but on a quick look at your code I have seen that you use ReflectionClass, which I try to not use at all for the Hydration. One reason why I use GeneratedHydrator. The Performance is just terrible with ReflectionClass and To use the StrategyPattern of the AbstractHydrator also offers more functionality for other purposes than just hydrating.

But thanks for your comment. I decided to write a simple extension for the GeneratedHydrator-Library.

**Comment by pounard** [comment]
> Thanks for your message, but on a quick look at your code I have seen that you use ReflectionClass

`ReflectionClass` is not that terrible for performances, I did a few benchmarks of my own. Regardless, I build an `HydrationPlan` but under the hood, it gets cached, because I sometime do use the `symfony/property-info` component and a custom docblock parser to introspect types when they are not available, and this was terrible for performances.

With proper caching, time taken by `ReflectionClass` and `property-info` component are basically reduced to 0 :)

**Pull request closed without merging**
