### PR TITLE
Upgrade nikic/php-parser and code-generator-utils to their latest versions

### LINKED ISSUE #79: Use php-parser v4
I just ran into #69 but with [nikic/php-parser](https://github.com/nikic/PHP-Parser/releases) v4, which was released in March.

I'm using [phpstan](https://github.com/phpstan/phpstan) - `phpstan/phpstan: 0.10` requires nikic/php-parser` v4...

FWIW:

1. I cloned this repo just to see if the tests might run with the v4 but `composer update -v` didn't upgrade `nikic/php-parser` because `ocramius/code-generator-utils` uses v3.
1. I just cloned `nikic/php-parser` v4 directly into `./vendor` but the tests failed with `Class 'PhpParser\BuilderAbstract' not found`.

It might be a bit of a job.

I'll look at downgrading `phpstan` to `0.9.2` to keep going.

### PR DESCRIPTION
**Pull request by WyriHaximus**
Fixes #79

### CODE REVIEW

**Comment by WyriHaximus** [comment]
:tada:

**Comment by WyriHaximus** [comment]
While I love to see this tagged sooner rather then later are you sure `2.3.0` is the best version since this does a major update for both dependencies?

**Comment by Ocramius** [comment]
> are you sure `2.3.0` is the best version since this does a major update for both dependencies?

Yes: none of the public API of this project changes, so a minor version bump is fine.

**Comment by WyriHaximus** [comment]
Ok great :+1: !

**Comment by Ocramius** [comment]
Ah, no, further (breaking) changes already made it into `master` via #77, so I have to tag a new major anyway

**Comment by WyriHaximus** [comment]
Haha ok, anyway I can help speed that up?

**Comment by Ocramius** [comment]
Currently doing that :-)

**Comment by WyriHaximus** [comment]
party-hard

**Pull request merged**
