### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by jguittard**
No dependency from zend-hydrator

### CODE REVIEW

**Comment by Ocramius** [comment]
@jguittard this library implements the hydrator interfaces

**Comment by jguittard** [comment]
Found a weak reference here yes : https://github.com/Ocramius/GeneratedHydrator/blob/master/src/GeneratedHydrator/ClassGenerator/HydratorGenerator.php#L71
Does it allow having ~1.1 | ^2.0 as a composer dependency?

**Comment by Ocramius** [comment]
@jguittard needs testing. In order to do that, please upgrade the `.travis.yml` to test max/min versions, like https://github.com/Ocramius/ProxyManager/blob/6c89b7bd6039d8047b1473e2074cb56baa4bc15d/.travis.yml#L10-L12

**Comment by Ocramius** [comment]
Note also https://github.com/Ocramius/ProxyManager/blob/6c89b7bd6039d8047b1473e2074cb56baa4bc15d/.travis.install.sh

**Comment by jguittard** [comment]
Will do that. Thanks

**Pull request closed without merging**
