### PR TITLE
Code style changes

### PR DESCRIPTION
**Pull request by malukenho**
The main changes were:

- Use array short syntax
- Use `::class`

### CODE REVIEW

**Comment by pounard** [comment]
I do agree with you, nevertheless I think it is mostly a sugar candy change, I'd like to postpone this on #59 review by @Ocramius, which is a more complicated merge if accepted, then convert the array syntax if it is wanted.

**Comment by malukenho** [comment]
@pounard Yep. That's was my ideia too.

**Comment by pounard** [comment]
I hope @Ocramius is alive somewhere :)

**Comment by Ocramius** [comment]
Agree with @pounard here - style changes just cause issues with merges, and are not strictly necessary. This is a type of change that can ONLY be applied when no other patches are pending.

**Pull request closed without merging**
