### PR TITLE
allow nikic/php-parser 1.1

### PR DESCRIPTION
**Pull request by remicollet**
As ocramius/code-generator-utils requires 1.0... not easy to test... have to hardly remplace vendor/nikic dir..

    $ phpunit
    PHPUnit 4.7-g7b9e68d by Sebastian Bergmann and contributors.
    
    Configuration read from /work/GIT/GeneratedHydrator/phpunit.xml.dist
    
    .............................I
    
    Time: 211 ms, Memory: 11.50Mb
    
    There was 1 incomplete test:
    
    1) GeneratedHydratorTest\Functional\HydratorFunctionalTest::testDisabledMethod
    Methods have to be disabled - currently only removing them
    
    /work/GIT/GeneratedHydrator/tests/GeneratedHydratorTest/Functional/HydratorFunctionalTest.php:94
    
    OK, but incomplete, skipped, or risky tests!
    Tests: 30, Assertions: 84, Incomplete: 1.

### CODE REVIEW

**Comment by remicollet** [comment]
As  "name": "ocramius/code-generator-utils", better way to test this

        "nikic/php-parser":              "~1.1",
        "ocramius/code-generator-utils": "dev-master"

Still ok.

**Comment by Ocramius** [comment]
Re-running the build since Ocramius/CodeGenerationUtils#3 was merged

**Comment by Ocramius** [comment]
:+1: thanks @remicollet

**Comment by Ocramius** [comment]
Tagged in [1.1.1](https://github.com/Ocramius/GeneratedHydrator/releases/tag/1.1.1)

**Comment by remicollet** [comment]
Great thanks for the merge and the tag!

**Pull request merged**
