### PR TITLE
[Missing tests] Only hydrate if data is in array

### PR DESCRIPTION
**Pull request by Danielss89**
Before adding/changing tests i'd like to know if this is something that could be merged?

### CODE REVIEW

**Comment by Ocramius** [comment]
@Danielss89 we discussed this before - the array must conform the hydrator specification, and it is not up to GeneratedHydrator to check for the existence of these keys.

Use a separate generated hydrator for that.

**Comment by Danielss89** [comment]
We did, i don't remember that :P
Well, ok then.

**Comment by Ocramius** [comment]
@Danielss89 think of this library (so far) as a `(Foo\Bar) ['the' => 'properties']` equivalent of `(object) ['the' => 'properties']`

**Comment by Danielss89** [comment]
Yeah, my thought was that it might vary what i wan't to populate into an object. And i don't always have all the fields of an object. Let's say it's an user, maybe i only want to change name and address, but not everything else(fields chosen on runtime).

**Comment by Ocramius** [comment]
Yeah, that would probably be done with a more specific hydrator then. This
is just copying data (all of it) into an object. The generic use-case is
stuff like mappers, not domain logic.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Pull request closed without merging**
